#!/usr/bin/env python3

import sys

if __name__ == "__main__":
    numbers = list(map(float, sys.stdin.read().strip().split()))
    average = sum(numbers) / len(numbers)
    print(f"Average: {average}")

