#!/usr/bin/env python3
import sys

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

if __name__ == "__main__":
    input_data = sys.stdin.read().strip().split()
    try:
        if len(input_data) != 2:
            print("?", file=sys.stdout)
            sys.exit(1)
        a = int(input_data[0])
        b = int(input_data[1])
        print(gcd(a, b))
    except ValueError:
        print("?", file=sys.stdout)
        sys.exit(1)

